import { execArgs } from './exec';
import { logger } from './logger';

export type PrBodyOptions = {
  baseBranch: string;
  logSnippet: string;
};

export const buildPrBody = (options: PrBodyOptions): string => {
  return `## Auto-generated Fix

This PR was automatically created to fix CI failures on **${options.baseBranch}**.

### Error Log
\`\`\`
${options.logSnippet}
\`\`\`

---
*Generated by self-healing-cli*`;
};

export const createPullRequest = (options: {
  title: string;
  body: string;
  base: string;
  head: string;
  cwd?: string;
}): string => {
  const result = execArgs(
    'gh',
    [
      'pr',
      'create',
      '--title',
      options.title,
      '--body',
      options.body,
      '--base',
      options.base,
      '--head',
      options.head,
    ],
    { cwd: options.cwd },
  );
  if (!result.ok) {
    logger.error('Failed to create PR:', result.stderr);
  }
  return result.stdout.trim();
};

export const commentOnCommit = (options: {
  sha: string;
  body: string;
  cwd?: string;
}): void => {
  const result = execArgs(
    'gh',
    [
      'api',
      'repos/{owner}/{repo}/commits/' + options.sha + '/comments',
      '-f',
      'body=' + options.body,
    ],
    { cwd: options.cwd },
  );
  if (!result.ok) {
    logger.error('Failed to comment on commit:', result.stderr);
  }
};
